### ISSUE TITLE
Jython support broken

### ISSUE THREAD

**Issue by ericfrederich** [tomerfiliba/rpyc#171]
Since pull request #166 Jython support is broken.
Using rpyc to get two different Python implementations talking to each other is extremely useful.
The ability to use rpyc to call from CPython into Java libraries is awesome... It'd be great to get it working again.

Here is the server and client output.

``` #
# SERVER
#
user@host:~/dev/rpyc/ $> JYTHONPATH=../plumbum ../jython/dist/bin/jython ./bin/rpyc_classic.py 
INFO:SLAVE/18812:server started on [0.0.0.0]:18812
INFO:SLAVE/18812:accepted 127.0.0.1:33661
INFO:SLAVE/18812:welcome [127.0.0.1]:33661
INFO:SLAVE/18812:goodbye [127.0.0.1]:33661
ERROR:SLAVE/18812:client connection terminated abruptly
Traceback (most recent call last):
  File "__pyclasspath__/rpyc/utils/server.py", line 172, in _authenticate_and_serve_client
    self._serve_client(sock2, credentials)
  File "__pyclasspath__/rpyc/utils/server.py", line 197, in _serve_client
    conn._init_service()
  File "__pyclasspath__/rpyc/core/protocol.py", line 162, in _init_service
    self._local_root.on_connect()
  File "__pyclasspath__/rpyc/core/service.py", line 145, in on_connect
    self._conn.modules = ModuleNamespace(self._conn.root.getmodule)
  File "__pyclasspath__/rpyc/core/protocol.py", line 512, in root
    self._remote_root = self.sync_request(consts.HANDLE_GETROOT)
  File "__pyclasspath__/rpyc/core/protocol.py", line 458, in sync_request
    self._send_request(seq, handler, args)
  File "__pyclasspath__/rpyc/core/protocol.py", line 254, in _send_request
    self._send(consts.MSG_REQUEST, seq, (handler, self._box(args)))
  File "__pyclasspath__/rpyc/core/protocol.py", line 244, in _send
    gc.disable()
NotImplementedError: can't disable Java GC
Exception in thread Thread-2:Traceback (most recent call last):
  File "/home/user/dev/jython/dist/Lib/threading.py", line 222, in _Thread__bootstrap
    self.run()
  File "/home/user/dev/jython/dist/Lib/threading.py", line 213, in run
    self._target(*self._args, **self._kwargs)
  File "__pyclasspath__/rpyc/utils/server.py", line 172, in _authenticate_and_serve_client
    self._serve_client(sock2, credentials)
  File "__pyclasspath__/rpyc/utils/server.py", line 197, in _serve_client
    conn._init_service()
  File "__pyclasspath__/rpyc/core/protocol.py", line 162, in _init_service
    self._local_root.on_connect()
  File "__pyclasspath__/rpyc/core/service.py", line 145, in on_connect
    self._conn.modules = ModuleNamespace(self._conn.root.getmodule)
  File "__pyclasspath__/rpyc/core/protocol.py", line 512, in root
    self._remote_root = self.sync_request(consts.HANDLE_GETROOT)
  File "__pyclasspath__/rpyc/core/protocol.py", line 458, in sync_request
    self._send_request(seq, handler, args)
  File "__pyclasspath__/rpyc/core/protocol.py", line 254, in _send_request
    self._send(consts.MSG_REQUEST, seq, (handler, self._box(args)))
  File "__pyclasspath__/rpyc/core/protocol.py", line 244, in _send
    gc.disable()
NotImplementedError: can't disable Java GC
user@host:~/dev/rpyc/ $> 


#
# CLIENT
#
user@host:~/dev/rpyc/ $> python
Python 2.7.5 (default, Feb 11 2014, 07:46:25) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-13)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import rpyc
>>> rpyc.classic.connect('localhost')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "rpyc/utils/classic.py", line 68, in connect
    return factory.connect(host, port, SlaveService, ipv6 = ipv6, keepalive = keepalive)
  File "rpyc/utils/factory.py", line 91, in connect
    return connect_stream(s, service, config)
  File "rpyc/utils/factory.py", line 52, in connect_stream
    return connect_channel(Channel(stream), service = service, config = config)
  File "rpyc/utils/factory.py", line 41, in connect_channel
    return Connection(service, channel, config = config)
  File "rpyc/core/protocol.py", line 157, in __init__
    self._init_service()
  File "rpyc/core/protocol.py", line 162, in _init_service
    self._local_root.on_connect()
  File "rpyc/core/service.py", line 145, in on_connect
    self._conn.modules = ModuleNamespace(self._conn.root.getmodule)
  File "rpyc/core/protocol.py", line 512, in root
    self._remote_root = self.sync_request(consts.HANDLE_GETROOT)
  File "rpyc/core/protocol.py", line 470, in sync_request
    self.serve(remaining_time)
  File "rpyc/core/protocol.py", line 408, in serve
    data = self._recv(timeout, wait_for_lock = True)
  File "rpyc/core/protocol.py", line 366, in _recv
    data = self._channel.recv()
  File "rpyc/core/channel.py", line 50, in recv
    header = self.stream.read(self.FRAME_HEADER.size)
  File "rpyc/core/stream.py", line 209, in read
    raise EOFError("connection closed by peer")
EOFError: connection closed by peer
>>> 
user@host:~/dev/rpyc/ $> 
```

**Comment by ericfrederich** [comment]
Any plans on fixing this?  Again, I think it is extremely useful to use rpyc on the same machine to get CPython and Jython working together.

**Comment by coldfix** [comment]
Hi,

should be fixed on current master. Sorry for the "slight" delay. If you're still using this package and experience any trouble, give me a shout-out. Thanks for pointing out the problem.

Best, Thomas

**Comment by conradek** [comment]
When using 3.4.2, I still see the original issue posted by ericfrederich.

From the server:

Exception in thread Thread-1:Traceback (most recent call last):
  File "/home/cek/jython/Lib/threading.py", line 222, in _Thread__bootstrap
    self.run()
  File "/home/cek/jython/Lib/threading.py", line 213, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cek/jython/Lib/site-packages/rpyc/utils/server.py", line 172, in _authenticate_and_serve_client
    self._serve_client(sock2, credentials)
  File "/home/cek/jython/Lib/site-packages/rpyc/utils/server.py", line 198, in _serve_client
    self._handle_connection(conn)
  File "/home/cek/jython/Lib/site-packages/rpyc/utils/server.py", line 204, in _handle_connection
    conn.serve_all()
  File "/home/cek/jython/Lib/site-packages/rpyc/core/protocol.py", line 423, in serve_all
    self.serve(0.1)
  File "/home/cek/jython/Lib/site-packages/rpyc/core/protocol.py", line 423, in serve_all
    self.serve(0.1)
  File "/home/cek/jython/Lib/site-packages/rpyc/core/protocol.py", line 415, in serve
    self._dispatch(data)
  File "/home/cek/jython/Lib/site-packages/rpyc/core/protocol.py", line 383, in _dispatch
    self._dispatch_request(seq, args)
  File "/home/cek/jython/Lib/site-packages/rpyc/core/protocol.py", line 343, in _dispatch_request
    self._send_reply(seq, res)
  File "/home/cek/jython/Lib/site-packages/rpyc/core/protocol.py", line 258, in _send_reply
    self._send(consts.MSG_REPLY, seq, self._box(obj))
  File "/home/cek/jython/Lib/site-packages/rpyc/core/protocol.py", line 245, in _send
    gc.disable()
NotImplementedError: can't disable Java GC

Any ideas?  Thanks!

**Comment by coldfix** [comment]
That's because the patch is only on master, not in the release so far. I'll create a new release tomorrow.

Best, Thomas

**Comment by conradek** [comment]
Ok, thanks!

**Comment by coldfix** [comment]
Done. Give me a call if you still have problems.

**Comment by conradek** [comment]
I have confirmed that this is fixed in 3.4.3.  Thanks!

**Comment by ericfrederich** [comment]
Thanks, I'm doing different things now and don't have an immediate need to use Java libraries from CPython.
I may give it a try in my free time just because I think it's a cool idea.

**Comment by ericfrederich** [comment]
I guess now that this is fixed it would make sense to add other Python implementations (jython, pypy) to tox/travis or whatever is running the unit tests here.

**Comment by conradek** [comment]
Hi Thomas,

I am running into issues when using jython and rpyc.  It seems like when a rpyc server under jython and is running for 15+ minutes, it runs out of memory and crashes.  When running the same server under python, the issue does not occur.

To duplicate:

- run the server: jython rpyc_server.py
- run the client: python rpyc_client.py

Here is the output from the server when the issue occurs:

Exception in thread "MainThread" java.lang.OutOfMemoryError: Java heap space
Exception in thread "Thread-1" java.lang.OutOfMemoryError: Java heap space

Just before the crash, the java process memory usage is ~545MB, CPU load is at ~30%.  At the start of the test it is ~64MB and 1% respectively.

I am running python 2.7.13, jython 2.7.1 and rpyc 3.4.3 on a Windows 10 PC.

I apologize if this should be in a new ticket!

-Conrad
[rpyc_tests.zip](https://github.com/tomerfiliba/rpyc/files/1271378/rpyc_tests.zip)
